package com.example.awoxapp.login

const val EDIT_TEXT_FIRST_NAME = "FIRST_NAME"
const val EDIT_TEXT_MIDDLE_NAME = "MIDDLE_NAME"
const val EDIT_TEXT_LAST_NAME = "LAST_NAME"
const val EDIT_TEXT_EMAIL = "EMAIL"
const val EDIT_TEXT_PHONE_NUMBER = "PHONE_NUMBER"
const val EDIT_TEXT_PASSWORD = "PASSWORD"
const val EDIT_TEXT_CONFIRM_PASSWORD ="CONFIRM_PASSWORD"